### ISSUE TITLE
Impossible de créer des repertoires avec des chiffres dans le nom

### ISSUE THREAD

**Issue by MiousseM** [croixbleueqc/python-devops-sccs#1]
Bonjour, 

Lorsque j'ai essayé de créer un repertoire client-travel-b2c-edge-api, je n'avais pas la possibilité de continuer dans le processus de création. À mon avis, la regex de validation du nom, devrait permettre les chiffres de 0-9 egalement, non?

https://github.com/croixbleueqc/python-devops-sccs/blob/f18caf141e396f392cab24e8d949bc8909239cf4/devops_sccs/provision.py#L152

**Comment by mickybart** [comment]
The line mentioned is just an example and is not an hard-coded value in python-devops-sccs.
The validator value depends on your organization configuration used in the devops-console-backend.

I'll keep the issue open just to propose a better validator example

**Comment by mickybart** [comment]
updated with commit edcfb72cb99bb6ee4cc39bf94a23b3400904d3dd
